### ISSUE TITLE
Feature: Have `gen-dev` also update `init/package.json`

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/builder-support#7]
For:
- [ ] archetype dep
- [ ] dev archetype dep

/cc @chaseadamsio @baer

**Comment by curiouslychase** [comment]
:+1: with 1000 burning :sunny:

**Comment by ryan-roemer** [comment]
Closing in lieu of https://github.com/FormidableLabs/builder-init/issues/18
